
 subroutine getsgrhm(sgnum,sgname)

   integer sgnum
   character*8 sgname

   sgname='        '
   if (sgnum.eq.  1) sgname='P1      '
   if (sgnum.eq.  2) sgname='P-1     '
   if (sgnum.eq.  3) sgname='P2      '
   if (sgnum.eq.  4) sgname='P21     '
   if (sgnum.eq.  5) sgname='C2      '
   if (sgnum.eq.  5) sgname='A2      '
   if (sgnum.eq.  5) sgname='B2      '
   if (sgnum.eq.  5) sgname='B2      '
   if (sgnum.eq.  5) sgname='C2      '
   if (sgnum.eq.  5) sgname='A2      '
   if (sgnum.eq.  6) sgname='Pm      '
   if (sgnum.eq.  6) sgname='Pm      '
   if (sgnum.eq.  6) sgname='Pm      '
   if (sgnum.eq.  7) sgname='Pc      '
   if (sgnum.eq.  7) sgname='Pa      '
   if (sgnum.eq.  7) sgname='Pb      '
   if (sgnum.eq.  7) sgname='Pb      '
   if (sgnum.eq.  7) sgname='Pc      '
   if (sgnum.eq.  7) sgname='Pa      '
   if (sgnum.eq.  7) sgname='Pn      '
   if (sgnum.eq.  7) sgname='Pn      '
   if (sgnum.eq.  7) sgname='Pn      '
   if (sgnum.eq.  8) sgname='Cm      '
   if (sgnum.eq.  8) sgname='Am      '
   if (sgnum.eq.  8) sgname='Bm      '
   if (sgnum.eq.  8) sgname='Bm      '
   if (sgnum.eq.  8) sgname='Cm      '
   if (sgnum.eq.  8) sgname='Am      '
   if (sgnum.eq.  9) sgname='Cc      '
   if (sgnum.eq.  9) sgname='Aa      '
   if (sgnum.eq.  9) sgname='Bb      '
   if (sgnum.eq.  9) sgname='Bb      '
   if (sgnum.eq.  9) sgname='Cc      '
   if (sgnum.eq.  9) sgname='Aa      '
   if (sgnum.eq. 10) sgname='P2/m    '
   if (sgnum.eq. 10) sgname='P2/m    '
   if (sgnum.eq. 10) sgname='P2/m    '
   if (sgnum.eq. 11) sgname='P21/m   '
   if (sgnum.eq. 11) sgname='P21/m   '
   if (sgnum.eq. 11) sgname='P21/m   '
   if (sgnum.eq. 12) sgname='C2/m    '
   if (sgnum.eq. 12) sgname='A2/m    '
   if (sgnum.eq. 12) sgname='B2/m    '
   if (sgnum.eq. 12) sgname='B2/m    '
   if (sgnum.eq. 12) sgname='C2/m    '
   if (sgnum.eq. 12) sgname='A2/m    '
   if (sgnum.eq. 13) sgname='P2/c    '
   if (sgnum.eq. 13) sgname='P2/a    '
   if (sgnum.eq. 13) sgname='P2/b    '
   if (sgnum.eq. 13) sgname='P2/b    '
   if (sgnum.eq. 13) sgname='P2/c    '
   if (sgnum.eq. 13) sgname='P2/a    '
   if (sgnum.eq. 13) sgname='P2/n    '
   if (sgnum.eq. 13) sgname='P2/n    '
   if (sgnum.eq. 13) sgname='P2/n    '
   if (sgnum.eq. 14) sgname='P21/c   '
   if (sgnum.eq. 14) sgname='P21/a   '
   if (sgnum.eq. 14) sgname='P21/b   '
   if (sgnum.eq. 14) sgname='P21/b   '
   if (sgnum.eq. 14) sgname='P21/c   '
   if (sgnum.eq. 14) sgname='P21/a   '
   if (sgnum.eq. 14) sgname='P21/n   '
   if (sgnum.eq. 14) sgname='P21/n   '
   if (sgnum.eq. 14) sgname='P21/n   '
   if (sgnum.eq. 15) sgname='C2/c    '
   if (sgnum.eq. 15) sgname='A2/a    '
   if (sgnum.eq. 15) sgname='B2/b    '
   if (sgnum.eq. 15) sgname='B2/b    '
   if (sgnum.eq. 15) sgname='C2/c    '
   if (sgnum.eq. 15) sgname='A2/a    '
   if (sgnum.eq. 16) sgname='P222    '
   if (sgnum.eq. 17) sgname='P2221   '
   if (sgnum.eq. 17) sgname='P2122   '
   if (sgnum.eq. 17) sgname='P2212   '
   if (sgnum.eq. 18) sgname='P21212  '
   if (sgnum.eq. 18) sgname='P22121  '
   if (sgnum.eq. 18) sgname='P21221  '
   if (sgnum.eq. 19) sgname='P212121 '
   if (sgnum.eq. 20) sgname='C2221   '
   if (sgnum.eq. 20) sgname='A2122   '
   if (sgnum.eq. 20) sgname='B2212   '
   if (sgnum.eq. 21) sgname='C222    '
   if (sgnum.eq. 21) sgname='A222    '
   if (sgnum.eq. 21) sgname='B222    '
   if (sgnum.eq. 22) sgname='F222    '
   if (sgnum.eq. 23) sgname='I222    '
   if (sgnum.eq. 24) sgname='I212121 '
   if (sgnum.eq. 25) sgname='Pmm2    '
   if (sgnum.eq. 25) sgname='P2mm    '
   if (sgnum.eq. 25) sgname='Pm2m    '
   if (sgnum.eq. 26) sgname='Pmc21   '
   if (sgnum.eq. 26) sgname='P21ma   '
   if (sgnum.eq. 26) sgname='Pb21m   '
   if (sgnum.eq. 26) sgname='Pcm21   '
   if (sgnum.eq. 26) sgname='P21am   '
   if (sgnum.eq. 26) sgname='Pm21b   '
   if (sgnum.eq. 27) sgname='Pcc2    '
   if (sgnum.eq. 27) sgname='P2aa    '
   if (sgnum.eq. 27) sgname='Pb2b    '
   if (sgnum.eq. 28) sgname='Pma2    '
   if (sgnum.eq. 28) sgname='P2mb    '
   if (sgnum.eq. 28) sgname='Pc2m    '
   if (sgnum.eq. 28) sgname='Pbm2    '
   if (sgnum.eq. 28) sgname='P2cm    '
   if (sgnum.eq. 28) sgname='Pm2a    '
   if (sgnum.eq. 29) sgname='Pca21   '
   if (sgnum.eq. 29) sgname='P21ab   '
   if (sgnum.eq. 29) sgname='Pc21b   '
   if (sgnum.eq. 29) sgname='Pbc21   '
   if (sgnum.eq. 29) sgname='P21ca   '
   if (sgnum.eq. 29) sgname='Pb21a   '
   if (sgnum.eq. 30) sgname='Pnc2    '
   if (sgnum.eq. 30) sgname='P2na    '
   if (sgnum.eq. 30) sgname='Pb2n    '
   if (sgnum.eq. 30) sgname='Pcn2    '
   if (sgnum.eq. 30) sgname='P2an    '
   if (sgnum.eq. 30) sgname='Pn2b    '
   if (sgnum.eq. 31) sgname='Pmn21   '
   if (sgnum.eq. 31) sgname='P21mn   '
   if (sgnum.eq. 31) sgname='Pn21m   '
   if (sgnum.eq. 31) sgname='Pnm21   '
   if (sgnum.eq. 31) sgname='P21nm   '
   if (sgnum.eq. 31) sgname='Pm21n   '
   if (sgnum.eq. 32) sgname='Pba2    '
   if (sgnum.eq. 32) sgname='P2cb    '
   if (sgnum.eq. 32) sgname='Pc2a    '
   if (sgnum.eq. 33) sgname='Pna21   '
   if (sgnum.eq. 33) sgname='P21nb   '
   if (sgnum.eq. 33) sgname='Pc21n   '
   if (sgnum.eq. 33) sgname='Pbn21   '
   if (sgnum.eq. 33) sgname='P21cn   '
   if (sgnum.eq. 33) sgname='Pn21a   '
   if (sgnum.eq. 34) sgname='Pnn2    '
   if (sgnum.eq. 34) sgname='P2nn    '
   if (sgnum.eq. 34) sgname='Pn2n    '
   if (sgnum.eq. 35) sgname='Cmm2    '
   if (sgnum.eq. 35) sgname='A2mm    '
   if (sgnum.eq. 35) sgname='Bm2m    '
   if (sgnum.eq. 36) sgname='Cmc21   '
   if (sgnum.eq. 36) sgname='A21ma   '
   if (sgnum.eq. 36) sgname='Bb21m   '
   if (sgnum.eq. 36) sgname='Ccm21   '
   if (sgnum.eq. 36) sgname='A21am   '
   if (sgnum.eq. 36) sgname='Bm21b   '
   if (sgnum.eq. 37) sgname='Ccc2    '
   if (sgnum.eq. 37) sgname='A2aa    '
   if (sgnum.eq. 37) sgname='Bb2b    '
   if (sgnum.eq. 38) sgname='Amm2    '
   if (sgnum.eq. 38) sgname='B2mm    '
   if (sgnum.eq. 38) sgname='Cm2m    '
   if (sgnum.eq. 39) sgname='Abm2    '
   if (sgnum.eq. 39) sgname='B2cm    '
   if (sgnum.eq. 39) sgname='Cm2a    '
   if (sgnum.eq. 39) sgname='Bma2    '
   if (sgnum.eq. 39) sgname='C2mb    '
   if (sgnum.eq. 39) sgname='Ac2m    '
   if (sgnum.eq. 40) sgname='Ama2    '
   if (sgnum.eq. 40) sgname='B2mb    '
   if (sgnum.eq. 40) sgname='Cc2m    '
   if (sgnum.eq. 40) sgname='Bbm2    '
   if (sgnum.eq. 40) sgname='C2cm    '
   if (sgnum.eq. 40) sgname='Am2a    '
   if (sgnum.eq. 41) sgname='Aba2    '
   if (sgnum.eq. 41) sgname='B2cb    '
   if (sgnum.eq. 41) sgname='Cc2a    '
   if (sgnum.eq. 41) sgname='Bba2    '
   if (sgnum.eq. 41) sgname='C2cb    '
   if (sgnum.eq. 41) sgname='Ac2a    '
   if (sgnum.eq. 42) sgname='Fmm2    '
   if (sgnum.eq. 42) sgname='F2mm    '
   if (sgnum.eq. 42) sgname='Fm2m    '
   if (sgnum.eq. 43) sgname='Fdd2    '
   if (sgnum.eq. 43) sgname='F2dd    '
   if (sgnum.eq. 43) sgname='Fd2d    '
   if (sgnum.eq. 44) sgname='Imm2    '
   if (sgnum.eq. 44) sgname='I2mm    '
   if (sgnum.eq. 44) sgname='Im2m    '
   if (sgnum.eq. 45) sgname='Iba2    '
   if (sgnum.eq. 45) sgname='I2cb    '
   if (sgnum.eq. 45) sgname='Ic2a    '
   if (sgnum.eq. 46) sgname='Ima2    '
   if (sgnum.eq. 46) sgname='I2mb    '
   if (sgnum.eq. 46) sgname='Ic2m    '
   if (sgnum.eq. 46) sgname='Ibm2    '
   if (sgnum.eq. 46) sgname='I2cm    '
   if (sgnum.eq. 46) sgname='Im2a    '
   if (sgnum.eq. 47) sgname='Pmmm    '
   if (sgnum.eq. 48) sgname='Pnnn    '
   if (sgnum.eq. 49) sgname='Pccm    '
   if (sgnum.eq. 49) sgname='Pmaa    '
   if (sgnum.eq. 49) sgname='Pbmb    '
   if (sgnum.eq. 50) sgname='Pban    '
   if (sgnum.eq. 50) sgname='Pncb    '
   if (sgnum.eq. 50) sgname='Pcna    '
   if (sgnum.eq. 51) sgname='Pmma    '
   if (sgnum.eq. 51) sgname='Pbmm    '
   if (sgnum.eq. 51) sgname='Pmcm    '
   if (sgnum.eq. 51) sgname='Pmam    '
   if (sgnum.eq. 51) sgname='Pmmb    '
   if (sgnum.eq. 51) sgname='Pcmm    '
   if (sgnum.eq. 52) sgname='Pnna    '
   if (sgnum.eq. 52) sgname='Pbnn    '
   if (sgnum.eq. 52) sgname='Pncn    '
   if (sgnum.eq. 52) sgname='Pnan    '
   if (sgnum.eq. 52) sgname='Pnnb    '
   if (sgnum.eq. 52) sgname='Pcnn    '
   if (sgnum.eq. 53) sgname='Pmna    '
   if (sgnum.eq. 53) sgname='Pbmn    '
   if (sgnum.eq. 53) sgname='Pncm    '
   if (sgnum.eq. 53) sgname='Pman    '
   if (sgnum.eq. 53) sgname='Pnmb    '
   if (sgnum.eq. 53) sgname='Pcnm    '
   if (sgnum.eq. 54) sgname='Pcca    '
   if (sgnum.eq. 54) sgname='Pbaa    '
   if (sgnum.eq. 54) sgname='Pbcb    '
   if (sgnum.eq. 54) sgname='Pbab    '
   if (sgnum.eq. 54) sgname='Pccb    '
   if (sgnum.eq. 54) sgname='Pcaa    '
   if (sgnum.eq. 55) sgname='Pbam    '
   if (sgnum.eq. 55) sgname='Pmcb    '
   if (sgnum.eq. 55) sgname='Pcma    '
   if (sgnum.eq. 56) sgname='Pccn    '
   if (sgnum.eq. 56) sgname='Pnaa    '
   if (sgnum.eq. 56) sgname='Pbnb    '
   if (sgnum.eq. 57) sgname='Pbcm    '
   if (sgnum.eq. 57) sgname='Pmca    '
   if (sgnum.eq. 57) sgname='Pbma    '
   if (sgnum.eq. 57) sgname='Pcmb    '
   if (sgnum.eq. 57) sgname='Pcam    '
   if (sgnum.eq. 57) sgname='Pmab    '
   if (sgnum.eq. 58) sgname='Pnnm    '
   if (sgnum.eq. 58) sgname='Pmnn    '
   if (sgnum.eq. 58) sgname='Pnmn    '
   if (sgnum.eq. 59) sgname='Pmmn    '
   if (sgnum.eq. 59) sgname='Pnmm    '
   if (sgnum.eq. 59) sgname='Pmnm    '
   if (sgnum.eq. 60) sgname='Pbcn    '
   if (sgnum.eq. 60) sgname='Pnca    '
   if (sgnum.eq. 60) sgname='Pbna    '
   if (sgnum.eq. 60) sgname='Pcnb    '
   if (sgnum.eq. 60) sgname='Pcan    '
   if (sgnum.eq. 60) sgname='Pnab    '
   if (sgnum.eq. 61) sgname='Pbca    '
   if (sgnum.eq. 61) sgname='Pcab    '
   if (sgnum.eq. 62) sgname='Pnma    '
   if (sgnum.eq. 62) sgname='Pbnm    '
   if (sgnum.eq. 62) sgname='Pmcn    '
   if (sgnum.eq. 62) sgname='Pnam    '
   if (sgnum.eq. 62) sgname='Pmnb    '
   if (sgnum.eq. 62) sgname='Pcmn    '
   if (sgnum.eq. 63) sgname='Cmcm    '
   if (sgnum.eq. 63) sgname='Amma    '
   if (sgnum.eq. 63) sgname='Bbmm    '
   if (sgnum.eq. 63) sgname='Bmmb    '
   if (sgnum.eq. 63) sgname='Ccmm    '
   if (sgnum.eq. 63) sgname='Amam    '
   if (sgnum.eq. 64) sgname='Cmca    '
   if (sgnum.eq. 64) sgname='Cmce    '
   if (sgnum.eq. 64) sgname='Abma    '
   if (sgnum.eq. 64) sgname='Bbcm    '
   if (sgnum.eq. 64) sgname='Bmab    '
   if (sgnum.eq. 64) sgname='Ccmb    '
   if (sgnum.eq. 64) sgname='Acam    '
   if (sgnum.eq. 65) sgname='Cmmm    '
   if (sgnum.eq. 65) sgname='Ammm    '
   if (sgnum.eq. 65) sgname='Bmmm    '
   if (sgnum.eq. 66) sgname='Cccm    '
   if (sgnum.eq. 66) sgname='Amaa    '
   if (sgnum.eq. 66) sgname='Bbmb    '
   if (sgnum.eq. 67) sgname='Cmma    '
   if (sgnum.eq. 67) sgname='Abmm    '
   if (sgnum.eq. 67) sgname='Bmcm    '
   if (sgnum.eq. 67) sgname='Bmam    '
   if (sgnum.eq. 67) sgname='Cmmb    '
   if (sgnum.eq. 67) sgname='Acmm    '
   if (sgnum.eq. 68) sgname='Ccca    '
   if (sgnum.eq. 68) sgname='Abaa    '
   if (sgnum.eq. 68) sgname='Bbcb    '
   if (sgnum.eq. 68) sgname='Bbab    '
   if (sgnum.eq. 68) sgname='Cccb    '
   if (sgnum.eq. 68) sgname='Acaa    '
   if (sgnum.eq. 69) sgname='Fmmm    '
   if (sgnum.eq. 70) sgname='Fddd    '
   if (sgnum.eq. 71) sgname='Immm    '
   if (sgnum.eq. 72) sgname='Ibam    '
   if (sgnum.eq. 72) sgname='Imcb    '
   if (sgnum.eq. 72) sgname='Icma    '
   if (sgnum.eq. 73) sgname='Ibca    '
   if (sgnum.eq. 73) sgname='Icab    '
   if (sgnum.eq. 74) sgname='Imma    '
   if (sgnum.eq. 74) sgname='Ibmm    '
   if (sgnum.eq. 74) sgname='Imcm    '
   if (sgnum.eq. 74) sgname='Imam    '
   if (sgnum.eq. 74) sgname='Immb    '
   if (sgnum.eq. 74) sgname='Icmm    '
   if (sgnum.eq. 75) sgname='P4      '
   if (sgnum.eq. 76) sgname='P41     '
   if (sgnum.eq. 77) sgname='P42     '
   if (sgnum.eq. 78) sgname='P43     '
   if (sgnum.eq. 79) sgname='I4      '
   if (sgnum.eq. 80) sgname='I41     '
   if (sgnum.eq. 81) sgname='P-4     '
   if (sgnum.eq. 82) sgname='I-4     '
   if (sgnum.eq. 83) sgname='P4/m    '
   if (sgnum.eq. 84) sgname='P42/m   '
   if (sgnum.eq. 85) sgname='P4/n    '
   if (sgnum.eq. 86) sgname='P42/n   '
   if (sgnum.eq. 87) sgname='I4/m    '
   if (sgnum.eq. 88) sgname='I41/a   '
   if (sgnum.eq. 89) sgname='P422    '
   if (sgnum.eq. 90) sgname='P4212   '
   if (sgnum.eq. 91) sgname='P4122   '
   if (sgnum.eq. 92) sgname='P41212  '
   if (sgnum.eq. 93) sgname='P4222   '
   if (sgnum.eq. 94) sgname='P42212  '
   if (sgnum.eq. 95) sgname='P4322   '
   if (sgnum.eq. 96) sgname='P43212  '
   if (sgnum.eq. 97) sgname='I422    '
   if (sgnum.eq. 98) sgname='I4122   '
   if (sgnum.eq. 99) sgname='P4mm    '
   if (sgnum.eq.100) sgname='P4bm    '
   if (sgnum.eq.101) sgname='P42cm   '
   if (sgnum.eq.102) sgname='P42nm   '
   if (sgnum.eq.103) sgname='P4cc    '
   if (sgnum.eq.104) sgname='P4nc    '
   if (sgnum.eq.105) sgname='P42mc   '
   if (sgnum.eq.106) sgname='P42bc   '
   if (sgnum.eq.107) sgname='I4mm    '
   if (sgnum.eq.108) sgname='I4cm    '
   if (sgnum.eq.109) sgname='I41md   '
   if (sgnum.eq.110) sgname='I41cd   '
   if (sgnum.eq.111) sgname='P-42m   '
   if (sgnum.eq.112) sgname='P-42c   '
   if (sgnum.eq.113) sgname='P-421m  '
   if (sgnum.eq.114) sgname='P-421c  '
   if (sgnum.eq.115) sgname='P-4m2   '
   if (sgnum.eq.116) sgname='P-4c2   '
   if (sgnum.eq.117) sgname='P-4b2   '
   if (sgnum.eq.118) sgname='P-4n2   '
   if (sgnum.eq.119) sgname='I-4m2   '
   if (sgnum.eq.120) sgname='I-4c2   '
   if (sgnum.eq.121) sgname='I-42m   '
   if (sgnum.eq.122) sgname='I-42d   '
   if (sgnum.eq.123) sgname='P4/mmm  '
   if (sgnum.eq.124) sgname='P4/mcc  '
   if (sgnum.eq.125) sgname='P4/nbm  '
   if (sgnum.eq.126) sgname='P4/nnc  '
   if (sgnum.eq.127) sgname='P4/mbm  '
   if (sgnum.eq.128) sgname='P4/mnc  '
   if (sgnum.eq.129) sgname='P4/nmm  '
   if (sgnum.eq.130) sgname='P4/ncc  '
   if (sgnum.eq.131) sgname='P42/mmc '
   if (sgnum.eq.132) sgname='P42/mcm '
   if (sgnum.eq.133) sgname='P42/nbc '
   if (sgnum.eq.134) sgname='P42/nnm '
   if (sgnum.eq.135) sgname='P42/mbc '
   if (sgnum.eq.136) sgname='P42/mnm '
   if (sgnum.eq.137) sgname='P42/nmc '
   if (sgnum.eq.138) sgname='P42/ncm '
   if (sgnum.eq.139) sgname='I4/mmm  '
   if (sgnum.eq.140) sgname='I4/mcm  '
   if (sgnum.eq.141) sgname='I41/amd '
   if (sgnum.eq.142) sgname='I41/acd '
   if (sgnum.eq.143) sgname='P3      '
   if (sgnum.eq.144) sgname='P31     '
   if (sgnum.eq.145) sgname='P32     '
   if (sgnum.eq.146) sgname='R3      '
   if (sgnum.eq.147) sgname='P-3     '
   if (sgnum.eq.148) sgname='R-3     '
   if (sgnum.eq.149) sgname='P312    '
   if (sgnum.eq.150) sgname='P321    '
   if (sgnum.eq.151) sgname='P3112   '
   if (sgnum.eq.152) sgname='P3121   '
   if (sgnum.eq.153) sgname='P3212   '
   if (sgnum.eq.154) sgname='P3221   '
   if (sgnum.eq.155) sgname='R32     '
   if (sgnum.eq.156) sgname='P3m1    '
   if (sgnum.eq.157) sgname='P31m    '
   if (sgnum.eq.158) sgname='P3c1    '
   if (sgnum.eq.159) sgname='P31c    '
   if (sgnum.eq.160) sgname='R3m     '
   if (sgnum.eq.161) sgname='R3c     '
   if (sgnum.eq.162) sgname='P-31m   '
   if (sgnum.eq.163) sgname='P-31c   '
   if (sgnum.eq.164) sgname='P-3m1   '
   if (sgnum.eq.165) sgname='P-3c1   '
   if (sgnum.eq.166) sgname='R-3m    '
   if (sgnum.eq.167) sgname='R-3c    '
   if (sgnum.eq.168) sgname='P6      '
   if (sgnum.eq.169) sgname='P61     '
   if (sgnum.eq.170) sgname='P65     '
   if (sgnum.eq.171) sgname='P62     '
   if (sgnum.eq.172) sgname='P64     '
   if (sgnum.eq.173) sgname='P63     '
   if (sgnum.eq.174) sgname='P-6     '
   if (sgnum.eq.175) sgname='P6/m    '
   if (sgnum.eq.176) sgname='P63/m   '
   if (sgnum.eq.177) sgname='P622    '
   if (sgnum.eq.178) sgname='P6122   '
   if (sgnum.eq.179) sgname='P6522   '
   if (sgnum.eq.180) sgname='P6222   '
   if (sgnum.eq.181) sgname='P6422   '
   if (sgnum.eq.182) sgname='P6322   '
   if (sgnum.eq.183) sgname='P6mm    '
   if (sgnum.eq.184) sgname='P6cc    '
   if (sgnum.eq.185) sgname='P63cm   '
   if (sgnum.eq.186) sgname='P63mc   '
   if (sgnum.eq.187) sgname='P-6m2   '
   if (sgnum.eq.188) sgname='P-6c2   '
   if (sgnum.eq.189) sgname='P-62m   '
   if (sgnum.eq.190) sgname='P-62c   '
   if (sgnum.eq.191) sgname='P6/mmm  '
   if (sgnum.eq.192) sgname='P6/mcc  '
   if (sgnum.eq.193) sgname='P63/mcm '
   if (sgnum.eq.194) sgname='P63/mmc '
   if (sgnum.eq.195) sgname='P23     '
   if (sgnum.eq.196) sgname='F23     '
   if (sgnum.eq.197) sgname='I23     '
   if (sgnum.eq.198) sgname='P213    '
   if (sgnum.eq.199) sgname='I213    '
   if (sgnum.eq.200) sgname='Pm-3    '
   if (sgnum.eq.201) sgname='Pn-3    '
   if (sgnum.eq.202) sgname='Fm-3    '
   if (sgnum.eq.203) sgname='Fd-3    '
   if (sgnum.eq.204) sgname='Im-3    '
   if (sgnum.eq.205) sgname='Pa-3    '
   if (sgnum.eq.206) sgname='Ia-3    '
   if (sgnum.eq.207) sgname='P432    '
   if (sgnum.eq.208) sgname='P4232   '
   if (sgnum.eq.209) sgname='F432    '
   if (sgnum.eq.210) sgname='F4132   '
   if (sgnum.eq.211) sgname='I432    '
   if (sgnum.eq.212) sgname='P4332   '
   if (sgnum.eq.213) sgname='P4132   '
   if (sgnum.eq.214) sgname='I4132   '
   if (sgnum.eq.215) sgname='P-43m   '
   if (sgnum.eq.216) sgname='F-43m   '
   if (sgnum.eq.217) sgname='I-43m   '
   if (sgnum.eq.218) sgname='P-43n   '
   if (sgnum.eq.219) sgname='F-43c   '
   if (sgnum.eq.220) sgname='I-43d   '
   if (sgnum.eq.221) sgname='Pm-3m   '
   if (sgnum.eq.222) sgname='Pn-3n   '
   if (sgnum.eq.223) sgname='Pm-3n   '
   if (sgnum.eq.224) sgname='Pn-3m   '
   if (sgnum.eq.225) sgname='Fm-3m   '
   if (sgnum.eq.226) sgname='Fm-3c   '
   if (sgnum.eq.227) sgname='Fd-3m   '
   if (sgnum.eq.228) sgname='Fd-3c   '
   if (sgnum.eq.229) sgname='Im-3m   '
   if (sgnum.eq.230) sgname='Ia-3d   '

   if (sgname.eq.'        ') then
      write(*,'(a,i4)') 'unknown space group number:',sgnum
      stop
   endif

 end subroutine getsgrhm
 
 
 
 
 logical function checksgrhm(sgnum,sgname)

   integer, intent(in) :: sgnum
   character*8, intent(in) :: sgname

   checksgrhm=.false.
   if ( (sgnum.eq.  1) .and.( sgname.eq.'P1      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  2) .and.( sgname.eq.'P-1     ') ) checksgrhm=.true.
   if ( (sgnum.eq.  3) .and.( sgname.eq.'P2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  4) .and.( sgname.eq.'P21     ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'C2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'A2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'B2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'B2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'C2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  5) .and.( sgname.eq.'A2      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  6) .and.( sgname.eq.'Pm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  6) .and.( sgname.eq.'Pm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  6) .and.( sgname.eq.'Pm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pc      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pa      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pb      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pb      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pc      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pa      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pn      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pn      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  7) .and.( sgname.eq.'Pn      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Cm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Am      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Bm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Bm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Cm      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  8) .and.( sgname.eq.'Am      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Cc      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Aa      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Bb      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Bb      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Cc      ') ) checksgrhm=.true.
   if ( (sgnum.eq.  9) .and.( sgname.eq.'Aa      ') ) checksgrhm=.true.
   if ( (sgnum.eq. 10) .and.( sgname.eq.'P2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 10) .and.( sgname.eq.'P2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 10) .and.( sgname.eq.'P2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 11) .and.( sgname.eq.'P21/m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 11) .and.( sgname.eq.'P21/m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 11) .and.( sgname.eq.'P21/m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'C2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'A2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'B2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'B2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'C2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 12) .and.( sgname.eq.'A2/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/c    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/c    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 13) .and.( sgname.eq.'P2/n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/c   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/a   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/b   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/b   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/c   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/a   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 14) .and.( sgname.eq.'P21/n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'C2/c    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'A2/a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'B2/b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'B2/b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'C2/c    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 15) .and.( sgname.eq.'A2/a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 16) .and.( sgname.eq.'P222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 17) .and.( sgname.eq.'P2221   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 17) .and.( sgname.eq.'P2122   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 17) .and.( sgname.eq.'P2212   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 18) .and.( sgname.eq.'P21212  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 18) .and.( sgname.eq.'P22121  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 18) .and.( sgname.eq.'P21221  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 19) .and.( sgname.eq.'P212121 ') ) checksgrhm=.true.
   if ( (sgnum.eq. 20) .and.( sgname.eq.'C2221   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 20) .and.( sgname.eq.'A2122   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 20) .and.( sgname.eq.'B2212   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 21) .and.( sgname.eq.'C222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 21) .and.( sgname.eq.'A222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 21) .and.( sgname.eq.'B222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 22) .and.( sgname.eq.'F222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 23) .and.( sgname.eq.'I222    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 24) .and.( sgname.eq.'I212121 ') ) checksgrhm=.true.
   if ( (sgnum.eq. 25) .and.( sgname.eq.'Pmm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 25) .and.( sgname.eq.'P2mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 25) .and.( sgname.eq.'Pm2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'Pmc21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'P21ma   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'Pb21m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'Pcm21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'P21am   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 26) .and. ( sgname.eq.'Pm21b   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 27) .and. ( sgname.eq.'Pcc2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 27) .and. ( sgname.eq.'P2aa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 27) .and. ( sgname.eq.'Pb2b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'Pma2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'P2mb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'Pc2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'Pbm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'P2cm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 28) .and. ( sgname.eq.'Pm2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'Pca21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'P21ab   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'Pc21b   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'Pbc21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'P21ca   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 29) .and. ( sgname.eq.'Pb21a   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'Pnc2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'P2na    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'Pb2n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'Pcn2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'P2an    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 30) .and. ( sgname.eq.'Pn2b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'Pmn21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'P21mn   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'Pn21m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'Pnm21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'P21nm   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 31) .and. ( sgname.eq.'Pm21n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 32) .and. ( sgname.eq.'Pba2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 32) .and. ( sgname.eq.'P2cb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 32) .and. ( sgname.eq.'Pc2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'Pna21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'P21nb   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'Pc21n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'Pbn21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'P21cn   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 33) .and. ( sgname.eq.'Pn21a   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 34) .and. ( sgname.eq.'Pnn2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 34) .and. ( sgname.eq.'P2nn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 34) .and. ( sgname.eq.'Pn2n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 35) .and. ( sgname.eq.'Cmm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 35) .and. ( sgname.eq.'A2mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 35) .and. ( sgname.eq.'Bm2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'Cmc21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'A21ma   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'Bb21m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'Ccm21   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'A21am   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 36) .and. ( sgname.eq.'Bm21b   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 37) .and. ( sgname.eq.'Ccc2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 37) .and. ( sgname.eq.'A2aa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 37) .and. ( sgname.eq.'Bb2b    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 38) .and. ( sgname.eq.'Amm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 38) .and. ( sgname.eq.'B2mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 38) .and. ( sgname.eq.'Cm2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'Abm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'B2cm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'Cm2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'Bma2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'C2mb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 39) .and. ( sgname.eq.'Ac2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'Ama2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'B2mb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'Cc2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'Bbm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'C2cm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 40) .and. ( sgname.eq.'Am2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'Aba2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'B2cb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'Cc2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'Bba2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'C2cb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 41) .and. ( sgname.eq.'Ac2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 42) .and. ( sgname.eq.'Fmm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 42) .and. ( sgname.eq.'F2mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 42) .and. ( sgname.eq.'Fm2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 43) .and. ( sgname.eq.'Fdd2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 43) .and. ( sgname.eq.'F2dd    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 43) .and. ( sgname.eq.'Fd2d    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 44) .and. ( sgname.eq.'Imm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 44) .and. ( sgname.eq.'I2mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 44) .and. ( sgname.eq.'Im2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 45) .and. ( sgname.eq.'Iba2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 45) .and. ( sgname.eq.'I2cb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 45) .and. ( sgname.eq.'Ic2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'Ima2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'I2mb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'Ic2m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'Ibm2    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'I2cm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 46) .and. ( sgname.eq.'Im2a    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 47) .and. ( sgname.eq.'Pmmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 48) .and. ( sgname.eq.'Pnnn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 49) .and. ( sgname.eq.'Pccm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 49) .and. ( sgname.eq.'Pmaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 49) .and. ( sgname.eq.'Pbmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 50) .and. ( sgname.eq.'Pban    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 50) .and. ( sgname.eq.'Pncb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 50) .and. ( sgname.eq.'Pcna    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pmma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pbmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pmcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pmam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pmmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 51) .and. ( sgname.eq.'Pcmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pnna    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pbnn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pncn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pnan    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pnnb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 52) .and. ( sgname.eq.'Pcnn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pmna    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pbmn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pncm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pman    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pnmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 53) .and. ( sgname.eq.'Pcnm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pcca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pbaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pbcb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pbab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pccb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 54) .and. ( sgname.eq.'Pcaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 55) .and. ( sgname.eq.'Pbam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 55) .and. ( sgname.eq.'Pmcb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 55) .and. ( sgname.eq.'Pcma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 56) .and. ( sgname.eq.'Pccn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 56) .and. ( sgname.eq.'Pnaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 56) .and. ( sgname.eq.'Pbnb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pbcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pmca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pbma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pcmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pcam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 57) .and. ( sgname.eq.'Pmab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 58) .and. ( sgname.eq.'Pnnm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 58) .and. ( sgname.eq.'Pmnn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 58) .and. ( sgname.eq.'Pnmn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 59) .and. ( sgname.eq.'Pmmn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 59) .and. ( sgname.eq.'Pnmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 59) .and. ( sgname.eq.'Pmnm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pbcn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pnca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pbna    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pcnb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pcan    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 60) .and. ( sgname.eq.'Pnab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 61) .and. ( sgname.eq.'Pbca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 61) .and. ( sgname.eq.'Pcab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pnma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pbnm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pmcn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pnam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pmnb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 62) .and. ( sgname.eq.'Pcmn    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Cmcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Amma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Bbmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Bmmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Ccmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 63) .and. ( sgname.eq.'Amam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Cmca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Cmce    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Abma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Bbcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Bmab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Ccmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 64) .and. ( sgname.eq.'Acam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 65) .and. ( sgname.eq.'Cmmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 65) .and. ( sgname.eq.'Ammm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 65) .and. ( sgname.eq.'Bmmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 66) .and. ( sgname.eq.'Cccm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 66) .and. ( sgname.eq.'Amaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 66) .and. ( sgname.eq.'Bbmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Cmma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Abmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Bmcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Bmam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Cmmb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 67) .and. ( sgname.eq.'Acmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Ccca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Abaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Bbcb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Bbab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Cccb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 68) .and. ( sgname.eq.'Acaa    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 69) .and. ( sgname.eq.'Fmmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 70) .and. ( sgname.eq.'Fddd    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 71) .and. ( sgname.eq.'Immm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 72) .and. ( sgname.eq.'Ibam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 72) .and. ( sgname.eq.'Imcb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 72) .and. ( sgname.eq.'Icma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 73) .and. ( sgname.eq.'Ibca    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 73) .and. ( sgname.eq.'Icab    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Imma    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Ibmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Imcm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Imam    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Immb    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 74) .and. ( sgname.eq.'Icmm    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 75) .and. ( sgname.eq.'P4      ') ) checksgrhm=.true.
   if ( (sgnum.eq. 76) .and. ( sgname.eq.'P41     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 77) .and. ( sgname.eq.'P42     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 78) .and. ( sgname.eq.'P43     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 79) .and. ( sgname.eq.'I4      ') ) checksgrhm=.true.
   if ( (sgnum.eq. 80) .and. ( sgname.eq.'I41     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 81) .and. ( sgname.eq.'P-4     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 82) .and. ( sgname.eq.'I-4     ') ) checksgrhm=.true.
   if ( (sgnum.eq. 83) .and. ( sgname.eq.'P4/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 84) .and. ( sgname.eq.'P42/m   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 85) .and. ( sgname.eq.'P4/n    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 86) .and. ( sgname.eq.'P42/n   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 87) .and. ( sgname.eq.'I4/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 88) .and. ( sgname.eq.'I41/a   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 89) .and. ( sgname.eq.'P422    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 90) .and. ( sgname.eq.'P4212   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 91) .and. ( sgname.eq.'P4122   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 92) .and. ( sgname.eq.'P41212  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 93) .and. ( sgname.eq.'P4222   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 94) .and. ( sgname.eq.'P42212  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 95) .and. ( sgname.eq.'P4322   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 96) .and. ( sgname.eq.'P43212  ') ) checksgrhm=.true.
   if ( (sgnum.eq. 97) .and. ( sgname.eq.'I422    ') ) checksgrhm=.true.
   if ( (sgnum.eq. 98) .and. ( sgname.eq.'I4122   ') ) checksgrhm=.true.
   if ( (sgnum.eq. 99) .and. ( sgname.eq.'P4mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq.100) .and. ( sgname.eq.'P4bm    ') ) checksgrhm=.true.
   if ( (sgnum.eq.101) .and. ( sgname.eq.'P42cm   ') ) checksgrhm=.true.
   if ( (sgnum.eq.102) .and. ( sgname.eq.'P42nm   ') ) checksgrhm=.true.
   if ( (sgnum.eq.103) .and. ( sgname.eq.'P4cc    ') ) checksgrhm=.true.
   if ( (sgnum.eq.104) .and. ( sgname.eq.'P4nc    ') ) checksgrhm=.true.
   if ( (sgnum.eq.105) .and. ( sgname.eq.'P42mc   ') ) checksgrhm=.true.
   if ( (sgnum.eq.106) .and. ( sgname.eq.'P42bc   ') ) checksgrhm=.true.
   if ( (sgnum.eq.107) .and. ( sgname.eq.'I4mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq.108) .and. ( sgname.eq.'I4cm    ') ) checksgrhm=.true.
   if ( (sgnum.eq.109) .and. ( sgname.eq.'I41md   ') ) checksgrhm=.true.
   if ( (sgnum.eq.110) .and. ( sgname.eq.'I41cd   ') ) checksgrhm=.true.
   if ( (sgnum.eq.111) .and. ( sgname.eq.'P-42m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.112) .and. ( sgname.eq.'P-42c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.113) .and. ( sgname.eq.'P-421m  ') ) checksgrhm=.true.
   if ( (sgnum.eq.114) .and. ( sgname.eq.'P-421c  ') ) checksgrhm=.true.
   if ( (sgnum.eq.115) .and. ( sgname.eq.'P-4m2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.116) .and. ( sgname.eq.'P-4c2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.117) .and. ( sgname.eq.'P-4b2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.118) .and. ( sgname.eq.'P-4n2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.119) .and. ( sgname.eq.'I-4m2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.120) .and. ( sgname.eq.'I-4c2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.121) .and. ( sgname.eq.'I-42m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.122) .and. ( sgname.eq.'I-42d   ') ) checksgrhm=.true.
   if ( (sgnum.eq.123) .and. ( sgname.eq.'P4/mmm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.124) .and. ( sgname.eq.'P4/mcc  ') ) checksgrhm=.true.
   if ( (sgnum.eq.125) .and. ( sgname.eq.'P4/nbm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.126) .and. ( sgname.eq.'P4/nnc  ') ) checksgrhm=.true.
   if ( (sgnum.eq.127) .and. ( sgname.eq.'P4/mbm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.128) .and. ( sgname.eq.'P4/mnc  ') ) checksgrhm=.true.
   if ( (sgnum.eq.129) .and. ( sgname.eq.'P4/nmm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.130) .and. ( sgname.eq.'P4/ncc  ') ) checksgrhm=.true.
   if ( (sgnum.eq.131) .and. ( sgname.eq.'P42/mmc ') ) checksgrhm=.true.
   if ( (sgnum.eq.132) .and. ( sgname.eq.'P42/mcm ') ) checksgrhm=.true.
   if ( (sgnum.eq.133) .and. ( sgname.eq.'P42/nbc ') ) checksgrhm=.true.
   if ( (sgnum.eq.134) .and. ( sgname.eq.'P42/nnm ') ) checksgrhm=.true.
   if ( (sgnum.eq.135) .and. ( sgname.eq.'P42/mbc ') ) checksgrhm=.true.
   if ( (sgnum.eq.136) .and. ( sgname.eq.'P42/mnm ') ) checksgrhm=.true.
   if ( (sgnum.eq.137) .and. ( sgname.eq.'P42/nmc ') ) checksgrhm=.true.
   if ( (sgnum.eq.138) .and. ( sgname.eq.'P42/ncm ') ) checksgrhm=.true.
   if ( (sgnum.eq.139) .and. ( sgname.eq.'I4/mmm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.140) .and. ( sgname.eq.'I4/mcm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.141) .and. ( sgname.eq.'I41/amd ') ) checksgrhm=.true.
   if ( (sgnum.eq.142) .and. ( sgname.eq.'I41/acd ') ) checksgrhm=.true.
   if ( (sgnum.eq.143) .and. ( sgname.eq.'P3      ') ) checksgrhm=.true.
   if ( (sgnum.eq.144) .and. ( sgname.eq.'P31     ') ) checksgrhm=.true.
   if ( (sgnum.eq.145) .and. ( sgname.eq.'P32     ') ) checksgrhm=.true.
   if ( (sgnum.eq.146) .and. ( sgname.eq.'R3      ') ) checksgrhm=.true.
   if ( (sgnum.eq.147) .and. ( sgname.eq.'P-3     ') ) checksgrhm=.true.
   if ( (sgnum.eq.148) .and. ( sgname.eq.'R-3     ') ) checksgrhm=.true.
   if ( (sgnum.eq.149) .and. ( sgname.eq.'P312    ') ) checksgrhm=.true.
   if ( (sgnum.eq.150) .and. ( sgname.eq.'P321    ') ) checksgrhm=.true.
   if ( (sgnum.eq.151) .and. ( sgname.eq.'P3112   ') ) checksgrhm=.true.
   if ( (sgnum.eq.152) .and. ( sgname.eq.'P3121   ') ) checksgrhm=.true.
   if ( (sgnum.eq.153) .and. ( sgname.eq.'P3212   ') ) checksgrhm=.true.
   if ( (sgnum.eq.154) .and. ( sgname.eq.'P3221   ') ) checksgrhm=.true.
   if ( (sgnum.eq.155) .and. ( sgname.eq.'R32     ') ) checksgrhm=.true.
   if ( (sgnum.eq.156) .and. ( sgname.eq.'P3m1    ') ) checksgrhm=.true.
   if ( (sgnum.eq.157) .and. ( sgname.eq.'P31m    ') ) checksgrhm=.true.
   if ( (sgnum.eq.158) .and. ( sgname.eq.'P3c1    ') ) checksgrhm=.true.
   if ( (sgnum.eq.159) .and. ( sgname.eq.'P31c    ') ) checksgrhm=.true.
   if ( (sgnum.eq.160) .and. ( sgname.eq.'R3m     ') ) checksgrhm=.true.
   if ( (sgnum.eq.161) .and. ( sgname.eq.'R3c     ') ) checksgrhm=.true.
   if ( (sgnum.eq.162) .and. ( sgname.eq.'P-31m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.163) .and. ( sgname.eq.'P-31c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.164) .and. ( sgname.eq.'P-3m1   ') ) checksgrhm=.true.
   if ( (sgnum.eq.165) .and. ( sgname.eq.'P-3c1   ') ) checksgrhm=.true.
   if ( (sgnum.eq.166) .and. ( sgname.eq.'R-3m    ') ) checksgrhm=.true.
   if ( (sgnum.eq.167) .and. ( sgname.eq.'R-3c    ') ) checksgrhm=.true.
   if ( (sgnum.eq.168) .and. ( sgname.eq.'P6      ') ) checksgrhm=.true.
   if ( (sgnum.eq.169) .and. ( sgname.eq.'P61     ') ) checksgrhm=.true.
   if ( (sgnum.eq.170) .and. ( sgname.eq.'P65     ') ) checksgrhm=.true.
   if ( (sgnum.eq.171) .and. ( sgname.eq.'P62     ') ) checksgrhm=.true.
   if ( (sgnum.eq.172) .and. ( sgname.eq.'P64     ') ) checksgrhm=.true.
   if ( (sgnum.eq.173) .and. ( sgname.eq.'P63     ') ) checksgrhm=.true.
   if ( (sgnum.eq.174) .and. ( sgname.eq.'P-6     ') ) checksgrhm=.true.
   if ( (sgnum.eq.175) .and. ( sgname.eq.'P6/m    ') ) checksgrhm=.true.
   if ( (sgnum.eq.176) .and. ( sgname.eq.'P63/m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.177) .and. ( sgname.eq.'P622    ') ) checksgrhm=.true.
   if ( (sgnum.eq.178) .and. ( sgname.eq.'P6122   ') ) checksgrhm=.true.
   if ( (sgnum.eq.179) .and. ( sgname.eq.'P6522   ') ) checksgrhm=.true.
   if ( (sgnum.eq.180) .and. ( sgname.eq.'P6222   ') ) checksgrhm=.true.
   if ( (sgnum.eq.181) .and. ( sgname.eq.'P6422   ') ) checksgrhm=.true.
   if ( (sgnum.eq.182) .and. ( sgname.eq.'P6322   ') ) checksgrhm=.true.
   if ( (sgnum.eq.183) .and. ( sgname.eq.'P6mm    ') ) checksgrhm=.true.
   if ( (sgnum.eq.184) .and. ( sgname.eq.'P6cc    ') ) checksgrhm=.true.
   if ( (sgnum.eq.185) .and. ( sgname.eq.'P63cm   ') ) checksgrhm=.true.
   if ( (sgnum.eq.186) .and. ( sgname.eq.'P63mc   ') ) checksgrhm=.true.
   if ( (sgnum.eq.187) .and. ( sgname.eq.'P-6m2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.188) .and. ( sgname.eq.'P-6c2   ') ) checksgrhm=.true.
   if ( (sgnum.eq.189) .and. ( sgname.eq.'P-62m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.190) .and. ( sgname.eq.'P-62c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.191) .and. ( sgname.eq.'P6/mmm  ') ) checksgrhm=.true.
   if ( (sgnum.eq.192) .and. ( sgname.eq.'P6/mcc  ') ) checksgrhm=.true.
   if ( (sgnum.eq.193) .and. ( sgname.eq.'P63/mcm ') ) checksgrhm=.true.
   if ( (sgnum.eq.194) .and. ( sgname.eq.'P63/mmc ') ) checksgrhm=.true.
   if ( (sgnum.eq.195) .and. ( sgname.eq.'P23     ') ) checksgrhm=.true.
   if ( (sgnum.eq.196) .and. ( sgname.eq.'F23     ') ) checksgrhm=.true.
   if ( (sgnum.eq.197) .and. ( sgname.eq.'I23     ') ) checksgrhm=.true.
   if ( (sgnum.eq.198) .and. ( sgname.eq.'P213    ') ) checksgrhm=.true.
   if ( (sgnum.eq.199) .and. ( sgname.eq.'I213    ') ) checksgrhm=.true.
   if ( (sgnum.eq.200) .and. ( sgname.eq.'Pm-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.201) .and. ( sgname.eq.'Pn-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.202) .and. ( sgname.eq.'Fm-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.203) .and. ( sgname.eq.'Fd-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.204) .and. ( sgname.eq.'Im-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.205) .and. ( sgname.eq.'Pa-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.206) .and. ( sgname.eq.'Ia-3    ') ) checksgrhm=.true.
   if ( (sgnum.eq.207) .and. ( sgname.eq.'P432    ') ) checksgrhm=.true.
   if ( (sgnum.eq.208) .and. ( sgname.eq.'P4232   ') ) checksgrhm=.true.
   if ( (sgnum.eq.209) .and. ( sgname.eq.'F432    ') ) checksgrhm=.true.
   if ( (sgnum.eq.210) .and. ( sgname.eq.'F4132   ') ) checksgrhm=.true.
   if ( (sgnum.eq.211) .and. ( sgname.eq.'I432    ') ) checksgrhm=.true.
   if ( (sgnum.eq.212) .and. ( sgname.eq.'P4332   ') ) checksgrhm=.true.
   if ( (sgnum.eq.213) .and. ( sgname.eq.'P4132   ') ) checksgrhm=.true.
   if ( (sgnum.eq.214) .and. ( sgname.eq.'I4132   ') ) checksgrhm=.true.
   if ( (sgnum.eq.215) .and. ( sgname.eq.'P-43m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.216) .and. ( sgname.eq.'F-43m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.217) .and. ( sgname.eq.'I-43m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.218) .and. ( sgname.eq.'P-43n   ') ) checksgrhm=.true.
   if ( (sgnum.eq.219) .and. ( sgname.eq.'F-43c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.220) .and. ( sgname.eq.'I-43d   ') ) checksgrhm=.true.
   if ( (sgnum.eq.221) .and. ( sgname.eq.'Pm-3m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.222) .and. ( sgname.eq.'Pn-3n   ') ) checksgrhm=.true.
   if ( (sgnum.eq.223) .and. ( sgname.eq.'Pm-3n   ') ) checksgrhm=.true.
   if ( (sgnum.eq.224) .and. ( sgname.eq.'Pn-3m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.225) .and. ( sgname.eq.'Fm-3m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.226) .and. ( sgname.eq.'Fm-3c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.227) .and. ( sgname.eq.'Fd-3m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.228) .and. ( sgname.eq.'Fd-3c   ') ) checksgrhm=.true.
   if ( (sgnum.eq.229) .and. ( sgname.eq.'Im-3m   ') ) checksgrhm=.true.
   if ( (sgnum.eq.230) .and. ( sgname.eq.'Ia-3d   ') ) checksgrhm=.true.

   return

 end function checksgrhm



