#!/bin/bash
files=`find -name referencexmu.dat |grep -v HUBBARD`
pd=`pwd`
if [ "X$1" == "X" ]
then
	cmd="feff"
else
	cmd='echo'
fi
pd=`pwd`
rm -f test.log
for file in $files
do
	dir=`dirname $file`
	cd $dir
	echo
	echo '##################################################################################################'
	echo '##################################################################################################'
	echo "Test: $file"
	echo '##################################################################################################'
	echo '##################################################################################################'
	$pd/../bin/$cmd |tee feff.out |sed 's/^/       /'
        # Get reference files.
        rfiles=`ls reference*`
	for rfile in $rfiles
	do
		fl=`echo $rfile |sed -e's/reference//g'`
		if [ "X$fl" == "Xxmu.dat" ]
		then
			grep -v '#' xmu.dat |nl > xmu1.dat 
			grep -v '#' $rfile |nl > xmu2.dat
			echo 
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$file: "
			echo 'xmu.dat' > rsqr.in
			echo 'referencexmu.dat' >> rsqr.in
			echo 1 >> rsqr.in
			echo 4 >> rsqr.in
			python2.7 $pd/rsqr.py < rsqr.in| awk '{if($1*100.0 < 0.1) print "pass"; else print "fail", $1*100.0}' 
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$file: " >> $pd/test.log
			python2.7 $pd/rsqr.py < rsqr.in| awk '{if($1*100.0 < 0.1) print "pass"; else print "fail", $1*100.0}' >> $pd/test.log
			echo
		else
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$file: "
			echo "Skipping for now ..."
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo
			echo -n "$file: " >> $pd/test.log
			echo "Skipping for now ..." >> $pd/test.log
		fi
	done
	cd $pd
done
