#!/bin/bash
. /opt/anaconda3/etc/profile.d/conda.sh
conda activate Corvus
conda env list
files=`find -name referencexmu.dat |grep -v HUBBARD`
pd=`pwd`
if [ "X$1" == "X" ]
then
	cmd="feff10test 20"
else
	cmd='echo'
fi
pd=`pwd`
rm -f test.log
for file in $files
do
	dir=`dirname $file`
	cd $dir
	echo
	echo '##################################################################################################'
	echo '##################################################################################################'
	echo "Test: $file"
	echo '##################################################################################################'
	echo '##################################################################################################'
	$cmd |tee feff.out |sed 's/^/       /'
        # Get reference files.
        rfiles=`ls reference*`
	for rfile in $rfiles
	do
		fl=`echo $rfile |sed -e's/reference//g'`
		if [ "X$fl" == "Xxmu.dat" ]
		then
			grep -v '#' xmu.dat |nl > xmu1.dat 
			grep -v '#' $rfile |nl > xmu2.dat
			echo 
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$fl: "
			echo 'xmu.dat' > rsqr.in
			echo 'referencexmu.dat' >> rsqr.in
			echo 1 >> rsqr.in
			echo 4 >> rsqr.in
			python $pd/rsqr.py < rsqr.in| awk '{if($1*100.0 < 0.1) print "pass"; else print "fail", $1*100.0}' 
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$file: " >> $pd/test.log
			python $pd/rsqr.py < rsqr.in| awk '{if($1*100.0 < 0.1) print "pass"; else print "fail", $1*100.0}' >> $pd/test.log
			echo
		else
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo -n "$fl: "
			echo "Skipping for now ..."
			echo '##################################################################################################'
			echo '##################################################################################################'
			echo
			echo -n "$fl: " >> $pd/test.log
			echo "Skipping for now ..." >> $pd/test.log
		fi
	done
	cd $pd
done
npass=`grep -c pass test.log`
nfail=`grep -c fail test.log`
ntot=`echo $npass $nfail |awk '{print $1+$2}'`
echo "PASSED: $npass/$ntot"
echo "FAILED: $nfail/$ntot" >> $pd/test.log
echo "PASSED: $npass/$ntot" >> $pd/test.log
echo "FAILED: $nfail/$ntot"
