#!/bin/bash -x
#
cd ../bin/
if [ "X$1" = "Xmpi" ]
then
	pd=`pwd`
#KJ	echo $pd
	echo '#!/bin/bash' > feffmpi	
	echo "FeffPath=$pd/MPI" >> feffmpi
        echo 'MPICOMMAND="mpirun -np $1 "' >> feffmpi
#	echo 'lamboot ${FeffPath}/mynodes;' >> feffmpi
	echo '$MPICOMMAND $FeffPath/rdinp' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/atomic' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/dmdw' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/opconsat' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/pot' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/ldos' >> feffmpi 
	echo '$MPICOMMAND $FeffPath/screen' >> feffmpi
	echo '$MPICOMMAND $FeffPath/xsph'  >> feffmpi
	echo '$MPICOMMAND $FeffPath/fms'  >> feffmpi
	echo '$MPICOMMAND $FeffPath/mkgtr'  >> feffmpi
	echo '$MPICOMMAND $FeffPath/path'  >> feffmpi
	echo '$MPICOMMAND $FeffPath/genfmt' >> feffmpi
	echo '$MPICOMMAND $FeffPath/ff2x' >> feffmpi
	echo '$MPICOMMAND $FeffPath/sfconv' >> feffmpi
	echo '$MPICOMMAND $FeffPath/compton'  >> feffmpi
	echo '$MPICOMMAND $FeffPath/eels' >> feffmpi
	echo '$MPICOMMAND $FeffPath/rhorrp'  >> feffmpi
#	echo 'wipe' >> feffmpi
	chmod u+x feffmpi
else
	pd=`pwd`
	echo '#!/bin/bash' > feff	
        echo "FeffPath=$pd/Seq" >> feff
	echo '$FeffPath/rdinp' >> feff
	echo '$FeffPath/dmdw' >> feff
	echo '$FeffPath/atomic' >> feff
	echo '$FeffPath/pot' >> feff
	echo '$FeffPath/ldos' >> feff
	echo '$FeffPath/screen' >> feff
        echo '$FeffPath/crpa'  >> feff
	echo '$FeffPath/opconsat' >> feff
	echo '$FeffPath/xsph' >> feff
	echo '$FeffPath/fms' >> feff
	echo '$FeffPath/mkgtr' >> feff
	echo '$FeffPath/path' >> feff
	echo '$FeffPath/genfmt' >> feff
	echo '$FeffPath/ff2x' >> feff
	echo '$FeffPath/sfconv' >> feff
	echo '$FeffPath/compton' >> feff
	echo '$FeffPath/eels' >> feff
	echo '$FeffPath/rhorrp' >> feff
	chmod u+x feff
fi
